name: Deploy Unified API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "api/unified_api/**"
      - "docker/Dockerfile.unified_api"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: endless-precept-479020-n9
      REGION: europe-west1
      SERVICE: symbiose-unified-api
      GAR_REPO: symbiose-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build & push image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/unified-api:latest"
          gcloud builds submit \
            --tag "$IMAGE" \
            --file docker/Dockerfile.unified_api .

      - name: Deploy
        run: |
          IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/unified-api:latest"
          gcloud run deploy $SERVICE \
            --image="$IMAGE" \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --set-env-vars=NEO4J_URI=${{ secrets.NEO4J_URI }},NEO4J_USER=${{ secrets.NEO4J_USER }},NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }},NEO4J_DATABASE=${{ secrets.NEO4J_DATABASE }},QDRANT_URL=${{ secrets.QDRANT_URL }},QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}
