name: Deploy Query API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tools/symbiose-query-api/**"
      - "docker/Dockerfile.query_api"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: endless-precept-479020-n9
      REGION: europe-west1
      SERVICE: symbiose-query-api
      GAR_REPO: symbiose-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build & push image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/query-api:latest"
          gcloud builds submit \
            --tag "$IMAGE" \
            --file docker/Dockerfile.query_api .

      - name: Deploy
        run: |
          IMAGE="europe-west1-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/query-api:latest"
          gcloud run deploy $SERVICE \
            --image="$IMAGE" \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --port=8081 \
            --set-env-vars=UNIFIED_API_URL=${{ secrets.UNIFIED_API_URL }},UNIFIED_API_TIMEOUT=30
