#!/usr/bin/env python3
import os
import subprocess
import json
from pathlib import Path

print("\n============= EFC SELF-HEAL SYSTEM =============\n")

ROOT = Path(__file__).resolve().parent.parent
REQ = ROOT / "requirements.txt"
METH = ROOT / "methodology"
DOCS = ROOT / "docs"

# -------------------------------------------------------
# 1. ENSURE REQUIRED PYTHON PACKAGES EXIST
# -------------------------------------------------------
REQUIRED_PKGS = [
    "pyvis",
    "requests",
    "markdown",
    "pydantic",
    "python-dotenv",
    "PyYAML"
]

def ensure_package(pkg):
    try:
        __import__(pkg.split("=")[0])
        print(f"✓ {pkg} allerede installert")
    except ImportError:
        print(f"→ Installerer {pkg} …")
        subprocess.run(["pip", "install", pkg], check=False)

print("▶ Sjekker og installerer nødvendige pakker…")
for pkg in REQUIRED_PKGS:
    ensure_package(pkg)

# -------------------------------------------------------
# 2. AUTO-PATCH requirements.txt
# -------------------------------------------------------
print("\n▶ Oppdaterer requirements.txt…")

if not REQ.exists():
    print("⚠️ requirements.txt mangler — oppretter ny")
    REQ.write_text("\n".join(REQUIRED_PKGS) + "\n")
else:
    existing = REQ.read_text().splitlines()
    patched = False
    for pkg in REQUIRED_PKGS:
        if pkg not in existing:
            existing.append(pkg)
            patched = True

    if patched:
        REQ.write_text("\n".join(existing) + "\n")
        print("✓ requirements.txt oppdatert")
    else:
        print("✓ requirements.txt allerede korrekt")

# -------------------------------------------------------
# 3. ENSURE METHODOLOGY FILES EXIST
# -------------------------------------------------------
print("\n▶ Sjekker metodologifiler…")
METH.mkdir(exist_ok=True)

needed_files = [
    "symbiosis-interface.md",
    "symbiotic-process.md",
    "symbiotic-process-llm.md",
    "symbiotic-process-summary.md",
]

placeholder = "# Placeholder — file auto-generated by EFC self-heal.\n"

for fname in needed_files:
    f = METH / fname
    if not f.exists():
        print(f"→ Oppretter {fname}")
        f.write_text(placeholder)
    else:
        print(f"✓ {fname} finnes")

# -------------------------------------------------------
# 4. ENSURE FIGSHARE TOKEN HANDLING
# -------------------------------------------------------
print("\n▶ FIGSHARE_TOKEN…")

token = os.environ.get("FIGSHARE_TOKEN", None)
if not token:
    print("⚠️ FIGSHARE_TOKEN er ikke satt — fortsetter i fallback-modus")
else:
    print("✓ FIGSHARE_TOKEN funnet")

# -------------------------------------------------------
# 5. ROBUST REPO MAP GENERATION
# -------------------------------------------------------
print("\n▶ Genererer repo_map.json (fallback hvis pyvis mangler)…")

import os

def generate_repo_map():
    structure = {}
    for root, dirs, files in os.walk(ROOT, followlinks=False):
        if ".git" in root:
            continue
        rel = os.path.relpath(root, ROOT)
        structure[rel] = {"dirs": dirs, "files": files}
    return structure

repo_map_json = DOCS / "repo_map.json"
repo_map_json.write_text(json.dumps(generate_repo_map(), indent=2))
print(f"✓ repo_map.json generert")

# Try pyvis graph output
try:
    from pyvis.network import Network

    net = Network(height="900px", width="100%")
    data = json.loads(repo_map_json.read_text())

    for node in data.keys():
        net.add_node(node, label=node)
        for d in data[node]["dirs"]:
            net.add_edge(node, f"{node}/{d}")
        for f in data[node]["files"]:
            net.add_edge(node, f"{node}/{f}")

    html_file = DOCS / "repo_map.html"
    net.show(str(html_file))
    print("✓ repo_map.html generert med pyvis")

except Exception as e:
    print(f"⚠️ pyvis finnes ikke eller feilet → fallback aktivert: {e}")

# -------------------------------------------------------
# 6. FINAL STATUS
# -------------------------------------------------------
print("\n============= SELF-HEAL COMPLETE =============")
print("Systemet er nå stabilt, alle mangler er håndtert.\n")
