#!/usr/bin/env python3
"""
generate_full_readmes.py

Universal README Generator for EFC Repository
---------------------------------------------
Features:
1. Scans entire main tree recursively.
2. Generates README.md for every folder (except root).
3. Updates existing README.md.
4. Detects project type (paper, schema, meta, api, theory, docs, code, misc).
5. Extracts abstract from JSON-LD if available.
6. Lists all files and subfolders.
7. Runs cleanly in GitHub Actions and locally.
"""

import os
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROOT_README = ROOT / "README.md"

# -------------------------------------------------------------
# Category inference
# -------------------------------------------------------------
def detect_category(path: Path):
    name = path.name.lower()

    if "papers" in path.parts:
        return "Scientific Paper — archived version with PDF + JSON-LD metadata."
    if "schema" in path.parts:
        return "Schema Layer — JSON-LD concepts, ontology, and semantic graph."
    if "meta" in path.parts:
        return "Meta Layer — cognition, reflection, methodology, symbiosis."
    if "api" in path.parts:
        return "API Layer — machine-readable endpoints and structured output."
    if "theory" in path.parts:
        return "Theory Layer — equations, definitions, and model foundations."
    if "figures" in path.parts:
        return "Figures and Visual Material."
    if "scripts" in path.parts:
        return "Automation Scripts — maintenance and system logic."
    if "docs" in path.parts:
        return "Documentation — rendered HTML, assets, and public-facing docs."

    return "Repository Folder"

# -------------------------------------------------------------
# Abstract extraction
# -------------------------------------------------------------
def extract_abstract(path: Path):
    """
    Extracts abstract from any .jsonld file inside the folder.
    Returns None if absent.
    """
    for jsonld in path.glob("*.jsonld"):
        try:
            data = json.loads(jsonld.read_text())
            abstract = data.get("abstract") or data.get("description")
            if abstract:
                return abstract.strip()
        except:
            continue
    return None

# -------------------------------------------------------------
# Directory scanning
# -------------------------------------------------------------
def scan_folder(path: Path):
    dirs = []
    files = []

    for p in sorted(path.iterdir()):
        if p.is_dir() and not p.name.startswith(".") and p.name not in ["__pycache__", ".git", ".github"]:
            dirs.append(p)
        elif p.is_file():
            files.append(p)

    return dirs, files

# -------------------------------------------------------------
# README generator
# -------------------------------------------------------------
def generate_readme(path: Path):
    category = detect_category(path)
    abstract = extract_abstract(path)
    dirs, files = scan_folder(path)

    text = f"# {path.name}\n\n"
    text += f"**{category}**\n\n"

    if abstract:
        text += "### Abstract\n"
        text += f"{abstract}\n\n"

    text += "This README was auto-generated by the EFC semantic system.\n\n"

    if dirs:
        text += "## Subfolders\n"
        for d in dirs:
            text += f"- `{d.name}/`\n"
        text += "\n"

    if files:
        text += "## Files\n"
        for f in files:
            text += f"- `{f.name}`\n"
        text += "\n"

    return text

# -------------------------------------------------------------
# Main routine
# -------------------------------------------------------------
def main():
    print("\n=== FULL TREE README GENERATION ===\n")
    print(f"Root README protected: {ROOT_README}\n")

    for current, dirs, files in os.walk(ROOT):
        path = Path(current)

        # Skip system folders
        if any(skip in path.parts for skip in [".git", ".github"]):
            continue

        # Skip root
        if path == ROOT:
            continue

        readme = path / "README.md"
        content = generate_readme(path)
        readme.write_text(content)

        print(f"✓ Updated README: {readme}")

    print("\nDONE — All READMEs updated.\n")

if __name__ == "__main__":
    main()
