#!/usr/bin/env python3
"""
update_all_readmes.py

EFC — Smart README Generator (with ROOT README PROTECTION)
----------------------------------------------------------
This script:

1. Updates README.md in ALL subfolders of the repository
2. Creates README.md for any folder missing one
3. **Never overwrites the root README.md**
4. Inserts short abstracts based on folder semantic category
5. Runs safely in GitHub Actions and locally
"""

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROOT_README = ROOT / "README.md"

# =========================================================
# HELPER FUNCTIONS
# =========================================================

def folder_category(path: Path):
    """Returns semantic category based on folder path."""
    name = path.name.lower()

    if name in ["theory", "formal"]:
        return "Theory Layer — formal physics, equations, and definitions."
    if name == "data":
        return "Data Layer — observational datasets used for validation."
    if name == "output":
        return "Validation Layer — results, figures, comparisons."
    if name in ["meta", "cognition", "symbiosis", "reflection", "meta-process"]:
        return "Meta–Cognition Layer — reflective process and symbiosis architecture."
    if name.startswith("schema"):
        return "Schema Layer — JSON-LD, ontology, semantic graph."
    if name == "api":
        return "API Layer — machine-readable endpoints for EFC concepts."
    if name == "app":
        return "Apps & Dashboards."
    if name == "scripts":
        return "Scripts — automation, autosync, generators."
    if name == "docs":
        return "Documentation — rendered files and HTML."

    return "Repository folder."

def scan_directory(path: Path):
    """Returns subfolders and files inside a directory."""
    dirs = []
    files = []
    for p in sorted(path.iterdir()):
        if p.is_dir() and not p.name.startswith(".") and p.name not in ["__pycache__", ".git", ".github"]:
            dirs.append(p)
        elif p.is_file() and p.name != "README.md":
            files.append(p)
    return dirs, files


def generate_readme_for_folder(folder: Path):
    """Generates README content based on folder."""
    dirs, files = scan_directory(folder)
    title = folder.name

    text = f"# {title}\n\n"
    text += f"**{folder_category(folder)}**\n\n"
    text += "This README was auto-generated by the `update_all_readmes.py` system.\n\n"

    if dirs:
        text += "## 📁 Subfolders\n"
        for d in dirs:
            text += f"- `{d.name}/`\n"
        text += "\n"

    if files:
        text += "## 📄 Files\n"
        for f in files:
            text += f"- `{f.name}`\n"
        text += "\n"

    text += "_Automatically maintained._\n"
    return text


def write_readme(folder: Path):
    """Writes or updates README.md inside a folder."""
    readme_path = folder / "README.md"

    # ROOT PROTECTION
    if folder == ROOT:
        print(f"⏭️  Skipping ROOT README (protected): {readme_path}")
        return

    content = generate_readme_for_folder(folder)
    readme_path.write_text(content)
    print(f"✓ Updated README: {readme_path}")


# =========================================================
# MAIN ROUTINE
# =========================================================

def update_all_readmes():
    print("\n========= UPDATE ALL READMEs (ROOT PROTECTED) =========\n")

    # 1. Leave ROOT README untouched
    print(f"ROOT README is protected: {ROOT_README}\n")

    # 2. Walk repository and update all others
    for current, dirs, files in os.walk(ROOT):
        current_path = Path(current)

        # Skip .git and .github
        if any(skip in current_path.parts for skip in [".git", ".github"]):
            continue

        write_readme(current_path)

    print("\nDone: All READMEs updated (root preserved).\n")


if __name__ == "__main__":
    update_all_readmes()
